# Configuration for probot-min-reviews - https://github.com/hitesh-coder/probot-minimum-reviews
_extends: .github

# Number of reviews required to mark the pull request as valid
reviewsUntilReady: 1

# Number of changes in the pull request to start enforcing the reviewsUntilReady rule
changesThreshold: 100

# Message to display when the commit status passes
reviewReadyMessage: 'No pending reviews'
docsReadyMessage: "Document changed"

# Message to display when the commit status fails
reviewNotReadyMessage: 'Pending review approvals'
docsNotReadyMessage: "Please change document"

#list of documents needs to change
listOfDocFiles: ["docs.md"]

# Status to set the commit to when waiting for reviews
# 'failure, error, and pending' are the suggested options
notReadyState: 'pending'
